'''
Problem 29: Distinct Powers
'''
from euler.utils.common import timeit

@timeit
def solve(limit: int = 100) -> int:
    """
    How many distinct terms are in the sequence generated by a^b for 2 <= a <= limit and 2 <= b <= limit?
    """
    # Use a set to store distinct values of a^b
    distinct_terms = {a**b for a in range(2, limit + 1) for b in range(2, limit + 1)}
    return len(distinct_terms)

if __name__ == "__main__":
    result = solve()
    print(f"Result: {result}")
