"""
Problem 45: Triangular, Pentagonal, and Hexagonal
"""

import math
from euler.utils.common import timeit


def is_pentagonal(x: int) -> bool:
    """
    Check if x is a pentagonal number.
    P_n = n(3n-1)/2 = x
    3n^2 - n - 2x = 0
    n = (1 + sqrt(1 + 24x)) / 6
    """
    if x <= 0:
        return False
    
    # Check if 1 + 24x is a perfect square
    disc = 1 + 24 * x
    root = math.isqrt(disc)
    
    if root * root != disc:
        return False
        
    # Check if (1 + root) is divisible by 6
    return (1 + root) % 6 == 0


@timeit
def solve():
    """
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    T_n = n(n+1)/2
    P_n = n(3n-1)/2
    H_n = n(2n-1)
    
    It can be verified that T_285 = P_165 = H_143 = 40755.
    Find the next triangle number that is also pentagonal and hexagonal.
    """
    # Key Insight: Every Hexagonal number is a Triangular number.
    # H_n = n(2n-1)
    # T_(2n-1) = (2n-1)(2n-1+1)/2 = (2n-1)(2n)/2 = n(2n-1) = H_n
    # So we only need to find a Hexagonal number that is also Pentagonal.
    
    # We start searching from n = 144 (since H_143 is the example given)
    n = 144
    while True:
        h_n = n * (2 * n - 1)
        if is_pentagonal(h_n):
            return h_n
        n += 1


if __name__ == "__main__":
    result = solve()
    print(f"Result: {result}")